services:
  back:
    build:
      context: ./BACK
    ports:
      - "8083:8083"
    networks:
      - batchcooking_network
    #environment:
     # - JWT_SECRET=${JWT_SECRET}
      #- JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}
    dns:
      - 8.8.8.8
      - 8.8.4.4

  front:
    build:
      context: ./FRONT
    ports:
      - "3000:80"
    networks:
      - batchcooking_network
    depends_on:
      - back
    environment:
      - REACT_APP_API_URL=http://back:8083