services:
  back:
    build:
      context: ./BACK
    ports:
      - "8083:8083"
    networks:
      - batchcooking_network
    #environment:
     # - JWT_SECRET=${JWT_SECRET}
      #- JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}

  front:
    build:
      context: ./FRONT
    ports:
      - "5173:80"
    networks:
      - batchcooking_network
    depends_on:
      - back

networks:
  batchcooking_network:
    driver: bridge
