spring.application.name=batchCooking

spring.config.import=optional:classpath:application-local.properties

server.port=8083

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=your_user
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuration JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=none

spring.data.mongodb.uri=${MONGO_URI}
