spring.application.name=batchCooking

spring.config.import=optional:classpath:application-local.properties

server.port=8083

# Configuration PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

# Configuration JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update

spring.data.mongodb.uri=${MONGO_URI}
